# build stage
FROM node:lts-alpine AS build-stage
WORKDIR /app

# pass your VITE_… args and bake them into the Vite build
ARG VITE_CLERK_PUBLISHABLE_KEY
ARG VITE_API_URL
ARG VITE_YJS_SERVER_URL
ENV VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}
ENV VITE_API_URL=${VITE_API_URL}
ENV VITE_YJS_SERVER_URL=${VITE_YJS_SERVER_URL}

COPY client/package*.json ./
RUN npm install
COPY client/ .
RUN npm run build

# production stage
FROM nginx:stable-alpine AS production-stage

# replace the default nginx.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

# copy built files
COPY --from=build-stage /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
