# nginx.conf
server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # serve existing files, or fall back to index.html
  location /api/ {
    proxy_pass https://api.luvonai.com;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
  
  # you can add caching rules for asset types if you like
  location ~* \.(js|css|png|svg|ico|json)$ {
    expires 1y;
    add_header Cache-Control "public";
  }
}
