server {
  listen       80;
  server_name  _;

  root   /usr/share/nginx/html;
  index  index.html;

  location / {
    # try the file, then folder, then fallback to index.html (SPA mode)
    try_files $uri $uri/ /index.html;
  }
}
